
name: 'Godot Engine 3.x HTML5 Export'
description: 'Godot Engine 3.x HTML5 export'
author: 'Simon Dalvai @dulvui'
branding:
  color: red
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  output-file-path:
    description: 'Path of the exported html files'
    required: false
    default: 'html5/index.html'
  create-export-preset-cfg:
    description: 'Set true if a simple export_presets.cfg should be created'
    required: false
    default: true
  godot-version:
    description: 'Godot Engine version'
    required: false
    default: '3.5.3'
  
runs:
  using: "composite"
  steps:

    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}

    - name: Download and config Godot Engine headless linux server and templates
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        
        sudo wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip
        chmod -R +rwx /home/runner/work/_temp
        chmod -R +rwx /usr/local/bin/godot
        sudo wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        sudo mkdir ~/.cache
        sudo mkdir -p ~/.config/godot
        sudo mkdir -p ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        sudo unzip Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip
        sudo mv Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip /usr/local/bin/godot
        sudo unzip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        sudo mv templates/* ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        sudo rm -f Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        godot -e -q

    - name: Create export presets config
      if: ${{ inputs.create-export-preset-cfg  == 'true' }}
      shell: bash
      run: sudo cp ${{ github.action_path }}/export_presets.cfg ${{ inputs.working-directory }}/export_presets.cfg

    - name: Create export paths directory structure
      shell: bash
      run: sudo mkdir -p "$(dirname ${{ inputs.output-file-path }})"

    - name: Export
      shell: bash
      run: sudo godot --path ${{ inputs.working-directory }} --export HTML5 ${{ inputs.output-file-path }}
